all:
  hosts:
  children:
    jenkins:
      hosts:
        jenkins-ctrl.ld-projects.com:
          ansible_ssh_user: ansible
          server_fqdn: jenkins-ctrl.ld-projects.com
    certhost:
      hosts:
        knowhere:
          ansible_ssh_user: tivan
          ansible_ssh_pass: "{{ certhost_ssh_pass }}"
