---
- name: pull certs by fqdn
  hosts: certhost
  vars_files:
    - vault
  roles:
    - role: certspull
      certs_remote_prefix: /home/tivan/certs
      certs_local_prefix: roles/revproxy/files/certs
...
