---
- hosts: jenkins
  remote_user: root
  vars:
    ansible_become_pass: "{{ ansible_ssh_pass }}"
    # can always override from command line, but would need changes in make keypair task
    keypair_files:
      - id_rsa
      - id_rsa.pub
  vars_files:
    - vault
    # not included in repo for obvious reasons; define/encrypt ansible_ssh_{user,pass} here if used
    #  adapted from http://stackoverflow.com/questions/21870083/specify-sudo-password-for-ansible/35945394
  become: yes
  become_method: sudo

  # certupdate done before nginx install due to config dependence; should be refined though
  roles:
    - role: java
      java_pkgs:
        - openjdk-11-jdk
    - role: jenkins
    - role: make_keypair
      target_user: jenkins
    - role: certupdate
      certs_local_prefix: roles/revproxy/files/certs
      certs_target_folder: /etc/ssl/nginx/certs
    - role: revproxy
      certs_target_folder: /etc/ssl/nginx/certs
