#NOTE: dest_prefix's role name must reflect requirements.yml setting
cert_user: tivan
src_prefix: "/home/{{ cert_user }}/certs"
dest_prefix: "roles/revproxy/files/certs"
cert_files:
  - cert.pem
  - chain.pem
  - fullchain.pem
  - privkey.pem

