---
# since certspull populates files/certs/<fqdn>, the following is required for the target:
#   - create cert directory
#   - copy privkey.pem and fullchain.pem to it
# a separate role can then put the ssl-enabled template on the target, check syntax, and restart nginx
- name: create ssl certs folder if not found
  ansible.builtin.file:
    path: /etc/ssl/nginx/certs
    state: directory
    mode: '0750'
  tags:
    - certupdate

- name: copy certs to target
  ansible.builtin.copy:
    src: "roles/nginx/files/certs/{{ server_fqdn }}/{{ item.filename }}"
    dest: "/etc/ssl/nginx/certs/{{ item.filename }}"
    mode: "{{ item.mode }}"
  loop:
    - filename: fullchain.pem
      mode: '0640'
    - filename: privkey.pem
      mode: '0400'
  tags:
    - certupdate
